### ISSUE TITLE
Add recommendation to release data (also) in non-proprietary format

### ISSUE THREAD

**Issue by andreamoro-git** [social-science-data-editors/template_README#24]
Not everyone can buy STATA, SAS, SPSS etc... to read datasets, and most people have just one of those

**Comment by larsvilhuber** [comment]
You do not have to buy/own Stata, SPSS, SAS to read these files. At least at the AEA, we have generically been lenient in practice, since there are open-source tools to reliably read Stata, SPSS, XLSX, and to some extent SAS (in R, Python, etc.). We have enforced it when data are impossible (some proprietary software used in macroeconomics) or really hard to read.  But it is correct to suggest that it be provided in non-proprietary/archival-friendly formats. Note that most often, the default format in social sciences (CSV) comes with a loss information (labels, value labels), and the use of DDI, HDF or similar descriptors is even worse....
